apiVersion: v1
kind: ConfigMap
metadata:
  name: apache-config
data:
  httpd.conf: |
    Alias /main "/usr/local/apache2/htdocs/main/"
    <Directory "/usr/local/apache2/htdocs/main">
      Options Indexes FollowSymLinks
      AllowOverride None
      Require all granted
    </Directory>