apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
      - name: my-app-container
        image: troitsart/apache-server:v1.0  # Замените на ваш образ
        ports:
        - containerPort: 80  # Порт, на котором контейнер слушает
